-- Correct older schema objects for Supabase's explicit Data API grant model.
-- The lifecycle exporter runs only with the protected service role.
grant select on table
  public.asset_media_jobs,
  public.audit_log,
  public.brand_voice_versions,
  public.brand_voices,
  public.campaigns,
  public.documents,
  public.generated_content,
  public.generated_content_events,
  public.generated_content_revisions,
  public.knowledge_chunks,
  public.knowledge_queries,
  public.knowledge_query_feedback,
  public.notebook_sessions,
  public.organization_feature_flags,
  public.product_asset_versions,
  public.product_assets,
  public.product_claims,
  public.product_template_assignments,
  public.product_templates,
  public.products,
  public.profiles,
  public.render_jobs,
  public.template_assets,
  public.template_families,
  public.template_import_runs,
  public.template_variants,
  public.template_versions,
  public.templates,
  public.uiux_measurement_events,
  public.organizations,
  public.onboarding_runs,
  public.onboarding_run_steps
  to service_role;
